"""add_risk_profile_fields_to_users

Revision ID: 17d3932dbea1
Revises: 2432393a80dc
Create Date: 2026-08-24 22:37:03.523623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d3932dbea1'
down_revision: Union[str, Sequence[str], None] = '2432393a80dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('risk_tolerance', sa.String(), nullable=True))
    op.add_column('users', sa.Column('risk_experience', sa.String(), nullable=True))
    op.add_column('users', sa.Column('goal_horizon_years', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'goal_horizon_years')
    op.drop_column('users', 'risk_experience')
    op.drop_column('users', 'risk_tolerance')
    # ### end Alembic commands ###
