"""Add section to budgets

Revision ID: 2432393a80dc
Revises: 83ff3c53dab0
Create Date: 2026-08-06 11:15:25.338413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2432393a80dc'
down_revision: Union[str, Sequence[str], None] = '83ff3c53dab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('section', sa.String(length=64), server_default='Buffer', nullable=False))
    op.alter_column('budgets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('budgets', 'monthly_limit',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.create_foreign_key(None, 'budgets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.create_foreign_key(None, 'budgets', 'users', ['user_id'], ['id'])
    op.alter_column('budgets', 'monthly_limit',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('budgets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('budgets', 'section')
    # ### end Alembic commands ###
